#!/bin/bash
sort -n | awk '
function pctile(sorted_array, pct) {
    count=length(sorted_array)
    idx=(pct * count) - 1
    idx=idx < 0 ? 0 : idx
    return (idx == int(idx)) ? sorted_array[int(idx)] : sorted_array[int(idx) + 1]
}
BEGIN{
    sum=0
    average=0
}
{
    sum+=$1
    if($1>max){
        max=$1
    }
    median_arr[n++]=$1
}
END{
    count=length(median_arr)
    if(count>0){
        average=sum/count
    }
    printf "sum %f\n", sum
    printf "count %f\n", count
    printf "average %f\n", average
    printf "min %f\n", pctile(median_arr, 0)
    printf "max %f\n", pctile(median_arr, 1)
    printf "pct50 %f\n", pctile(median_arr, .5)
    printf "pct75 %f\n", pctile(median_arr, .75)
    printf "pct90 %f\n", pctile(median_arr, .90)
    printf "pct95 %f\n", pctile(median_arr, .95)
    printf "pct99 %f\n", pctile(median_arr, .99)
    printf "pct999 %f\n", pctile(median_arr, .999)
}' | column -t
