#!/usr/bin/env bash

cmd=$1

if [[ $cmd == "--help" ]] || [[ -z $cmd ]]
then
    echo "chklst -- check list helper for various topics

Usage: chklst [topic] [--help] [--topics]"
    exit 0 
fi

if [[ $cmd == "--topics" ]]
then
    echo "codereview
completetask
rca"
    exit 0 
fi

function ask_questions {
    questions=$1
    results=""
    while read question <&3
    do
        echo -n $question
        while True
        do
            read  -s -p " Y/N:" -n 1 resp
            if [[ $resp =~ [Yy] ]]
            then
                echo " ✅"
                results="${results}✅"
                break
            elif [[ $resp =~ [Nn] ]]
            then
                echo " ❌"
                results="${results}❌"
                break
            fi
        done
    done 3<<< "$questions"
    
    echo "
Results:"
    idx=0
    while read question 
    do
        echo $question-${results:$idx:1}
        idx=$((idx+1))
    done <<< "$questions" | column -t -s'-'
}

codereview="Is the change necessary?
Are there unit tests for the change?
Does the change fix the issue?"

if [[ $cmd == "codereview" ]]
then
    ask_questions "$codereview"
fi
