#!/usr/bin/env python3
import sys
import re
from datetime import timedelta
import iso8601

def main():
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else None
    iso_matcher = re.compile('[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:Z|[+\-][0-9]{2}:[0-9]{2})')
    for line in sys.stdin:
        diff = None
        matches = iso_matcher.findall(line)
        for match in matches[:limit]:
            d = iso8601.parse_date(match)
            if not diff:
                diff = d
            else:
                diff -= d
        if isinstance(diff, timedelta):
            print(line.rstrip() + " " + str(int(diff.total_seconds())))
        else:
            print(line.rstrip())

if __name__ == '__main__':
    main()
