#!/usr/bin/env python3
import sys
import re
from datetime import timedelta
import iso8601

def main():
    iso_matcher = re.compile('[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:Z|[+\-][0-9]{2}:[0-9]{2})')
    for line in sys.stdin:
        diff = None
        matches = iso_matcher.findall(line)
        if len(matches) > 1:
            first_date, last_date = [iso8601.parse_date(m) for m in matches[:2]]
            diff = abs(int((first_date - last_date).total_seconds()))
            print(line.rstrip() + " " + str(diff))
        else:
            print(line.rstrip())

if __name__ == '__main__':
    main()
